Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from dashboard import views


router = DefaultRouter()
router.register(r'categories', views.CategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/api/', include('dashboard.urls')),
    path('front/', include('front.urls')),
    path('', include('main.urls')),
    path('', include(router.urls)),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from .views import CategoryListCreateView, CategoryRetrieveUpdateDestroyView


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('category-create', views.create_category, name='create_category'),
    path('category-list', views.list_category, name='list_category'),
    path('category-detail/<int:id>/', views.detail_category, name='detail_category'),
    path('category-update/<int:id>/', views.update_category, name='update_category'),
    path('post-create/', views.create_post, name='create_post'),
    path('regions/', views.regions, name='regions'),
    path('log-in', views.log_in, name='log_in'),
    path('categories/', CategoryListCreateView.as_view(), name='category_list_create'),
    path('categories/<int:pk>/', CategoryRetrieveUpdateDestroyView.as_view(), name='category_retrieve_update_destroy'),


]

front/urls.py
from django.urls import path
from . import views


app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('log-in', views.log_in, name='log_in'),

]

main/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('front.urls')),
    
]

main/models.py
from rest_framework import serializers
from django.db import models
from django.contrib.auth.models import User


class Region(models.Model):
    name = models.CharField(max_length=255, unique=True)


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField()
    banner_img = models.ImageField(upload_to='post-baner/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='post-img/')


class PostVideo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    video = models.FileField(upload_to='post-vido/')
    video_url = models.URLField(blank=True, null=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

dashboard/views.py
from django.shortcuts import render, redirect
from main import models
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from rest_framework import viewsets
from main.models import Category
from . import CategorySerializer

class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()  # Queryset for all categories
    serializer_class = CategorySerializer  # Serializer for data conversion

    def perform_create(self, serializer):
        # Optional: Customize create logic here (e.g., set defaults)
        serializer.save()










# @login_required(login_url='dashboard:log_in')
def index(request):

    return render(request, 'dashboard\index.html')


def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('dashboard:index')
        else:
            return render(request, 'dashboard/auth/login.html', {'error': 'Invalid credentials. Please try again.'})

    return render(request, 'dashboard/auth/login.html')



def create_category(request):
    if request.method == "POST":       
        name= request.POST['name']
        models.Category.objects.create(
            name=name,
        
        )   
    return render(request, 'dashboard/category/create.html')


def detail_category(request, id):
    category = models.Category.objects.get(id=id)
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/detail.html', context)

def list_category(request):
    category = models.Category.objects.all()
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/list.html', context)


def update_category(request, id):
    category = models.Category.objects.get(id=id)
    if request.method == 'POST':
        category.name = request.POST['name']
        category.save()
        return redirect('dashboard:detail_category', category.id )      
    return render(request, 'dashboard/category/update.hml', {'category':category})


def detail_category(request, id):
    category = models.Category.objects.get(id=id)
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/detail.html', context)



def delete_category(request, id):
    models.Category.objects.get(id=id).delete()
    return redirect('list_category')
    


def create_post(request):
    regions = models.Region.objects.all()
    category = models.Category.objects.all()
    context = {
        'regions':regions,
        'category':category
    }
    if request.method == 'POST':
        models.Post.objects.create(
            

           
            name = request.POST['name'],
            body = request.POST['body'],
            banner_img = request.POST['banner_img'],

        )

   
    return render(request, 'dashboard/post/create.html', context)

# def product_create(request):
#     categorys = models.Category.objects.all()
#     context = {'categorys':categorys}
#     if request.method == 'POST':
#         delivery = True if request.POST.get('delivery') else False

#         models.Product.objects.create(
#             category_id = request.POST['category_id'],
#             name = request.POST['name'],
#             body = request.POST['body'],
#             price = request.POST['price'],
#             banner_img = request.FILES['banner_img'],
#             quantity = request.POST['quantity'],
#             delivery = delivery
#         )
#         return redirect('dashboard:product_list')
#     return render(request, 'dashboard/product/create.html', context)




def regions(request, id):
    regions = models.Region.objects.all()
    
    return render(request, 'dashboard/post/regions.html', {'regions': regions})













front/views.py
from django.shortcuts import render, redirect
from main import models
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    regions = models.Region.objects.all()
    categories = models.Category.objects.all()
    context = {
        'regions':regions,
        'categories':categories
    }

    return render(request, 'front/index.html', context)



def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('dashboard:index')
        else:
            # Add the following line to render the login template with an error message
            return render(request, 'dashboard/auth/login.html', {'error': 'Invalid credentials. Please try again.'})

    return render(request, 'dashboard/auth/login.html')

main/views.py
from django.shortcuts import render
from . import models

def index(request):
     regions = models.Region.objects.all()
     context = {
          'regions':regions
     }

     return render(request, 'front/index.html', context)

templates/dashboard/category/create.html
{% extends 'dashboard/base.html' %}
{% block content %}



<div class="main-content app-content mt-0" >
    
                  
    <!-- content -->

    <div class="form-floating floating-label1">
        <form method="post">
            {% csrf_token %}

        <input type="text"textarea class="form-control" name="name" placeholder="Category" id="floatingTextarea2" style="height: 100px"></textarea>
        

            <div class="col-md-12">
                <button type="submit" class="btn btn-success rounded-pill">Success</button>
            </div>
        </form>
    </div>

</div>









{% endblock %}



templates/dashboard/category/detail.html
{% extends 'dashboard/base.html' %}
{% block content %}






<div class="main-content app-content mt-0">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                     <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mb-3">Category haqida batafsil</h4>
    
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead class="table-light">
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><strong>Name</strong></td>
                                            <td>{{category.name}}</td>
                                        </tr>
                                        
                                        </tbody>
                                    </table>
                                </div>
                                <!-- end table-responsive -->
    
                            </div>
                        </div>
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
        </div>
        <!-- container -->

    </div>












{% endblock %}

templates/dashboard/category/list.html
{% extends 'dashboard/base.html' %}
{% block content %}

   <!-- PAGE-HEADER -->
   <div class="page-header">
    <h1 class="page-title">Editor-Table</h1>
   
   </div>
<!-- PAGE-HEADER END -->

<!-- Row -->
<div class="main-content app-content mt-0">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Basic Edit Table</h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered border text-nowrap mb-0" id="basic-edit">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>   
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in category %}
                            <tr>
                                <td>#</td> 
                                <td>{{c.name}}</td>
                                <td><a href="{% url 'dashboard:detail_category' c.id %}">Details</a></td>
                                <td>
                                    <button id="bEdit" type="button" class="btn btn-sm btn-primary">
                                        <span class="fe fe-edit"> </span>
                                    </button>
                                
                                    <button id="bDel" type="button" class="btn  btn-sm btn-danger">
                                         <span class="fe fe-trash-2"> </span>
                                    </button>
                                </td> 

                            </tr>
                            {% endfor %}
   
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Row -->








{% endblock %}

templates/dashboard/category/update.html
{% extends 'dashboard/base.html' %}
{% block content %}


















{% endblock %}

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
            <!--app-content open-->
            <div class="main-content app-content mt-0">
                <div class="side-app">

                    <!-- CONTAINER -->
                    <div class="main-container container-fluid">

                        <!-- PAGE-HEADER -->
                        <div class="page-header">
                            <h1 class="page-title">Dashboard 01</h1>
                            <div>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Dashboard 01</li>
                                </ol>
                            </div>
                        </div>
                        <!-- PAGE-HEADER END -->

                        <!-- ROW-1 -->
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xl-12">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xl-3">
                                        <div class="card overflow-hidden">
                                            <div class="card-body">
                                                <div class="d-flex">
                                                    <div class="mt-2">
                                                        <h6 class="">Total Users</h6>
                                                        <h2 class="mb-0 number-font">44,278</h2>
                                                    </div>
                                                    <div class="ms-auto">
                                                        <div class="chart-wrapper mt-1">
                                                            <canvas id="saleschart"
                                                                class="h-8 w-9 chart-dropshadow"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                                <span class="text-muted fs-12"><span class="text-secondary"><i
                                                            class="fe fe-arrow-up-circle  text-secondary"></i> 5%</span>
                                                    Last week</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xl-3">
                                        <div class="card overflow-hidden">
                                            <div class="card-body">
                                                <div class="d-flex">
                                                    <div class="mt-2">
                                                        <h6 class="">Total Profit</h6>
                                                        <h2 class="mb-0 number-font">67,987</h2>
                                                    </div>
                                                    <div class="ms-auto">
                                                        <div class="chart-wrapper mt-1">
                                                            <canvas id="leadschart"
                                                                class="h-8 w-9 chart-dropshadow"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                                <span class="text-muted fs-12"><span class="text-pink"><i
                                                            class="fe fe-arrow-down-circle text-pink"></i> 0.75%</span>
                                                    Last 6 days</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xl-3">
                                        <div class="card overflow-hidden">
                                            <div class="card-body">
                                                <div class="d-flex">
                                                    <div class="mt-2">
                                                        <h6 class="">Total Expenses</h6>
                                                        <h2 class="mb-0 number-font">$76,965</h2>
                                                    </div>
                                                    <div class="ms-auto">
                                                        <div class="chart-wrapper mt-1">
                                                            <canvas id="profitchart"
                                                                class="h-8 w-9 chart-dropshadow"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                                <span class="text-muted fs-12"><span class="text-green"><i
                                                            class="fe fe-arrow-up-circle text-green"></i> 0.9%</span>
                                                    Last 9 days</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xl-3">
                                        <div class="card overflow-hidden">
                                            <div class="card-body">
                                                <div class="d-flex">
                                                    <div class="mt-2">
                                                        <h6 class="">Total Cost</h6>
                                                        <h2 class="mb-0 number-font">$59,765</h2>
                                                    </div>
                                                    <div class="ms-auto">
                                                        <div class="chart-wrapper mt-1">
                                                            <canvas id="costchart"
                                                                class="h-8 w-9 chart-dropshadow"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                                <span class="text-muted fs-12"><span class="text-warning"><i
                                                            class="fe fe-arrow-up-circle text-warning"></i> 0.6%</span>
                                                    Last year</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- ROW-1 END -->
                       
                    </div>
                    <!-- CONTAINER END -->
                </div>
            </div>
            <!--app-content close-->
{% endblock %}

templates/dashboard/post/create.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class="main-content app-content mt-0">
    <h1>Create a new post</h1>
    <form method="post" >
        {% csrf_token %}
        <div class="form-group">
            <label for="author">Title</label>
            <input type="text" id="author" name="title" required class="form-control">
        </div>
        <div class="form-group">
            <label for="region">Category</label>
            <select id="region" name="category" required class="form-control">
                {% for category in category %}
                <option value="{{category.id}}" >{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="region">Region:</label>
            <select id="region" name="region" required class="form-control">
                {% for region in regions %}
                <option value="{{region.id}}">{{ region.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Batafsil</label>
            <div class="col-sm-10">
                <textarea name="body" class="form-control" cols="30" rows="10"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Banner rasm</label>
            <div class="col-sm-10">
                <input type="file" class="form-control" id="inputPassword3" name="banner_img">
            </div>
        
        <button type="submit" class="btn btn-success rounded-pill">Success</button>
    </form>
</div>




{% endblock %}

templates/dashboard/post/regions.html
{% extends 'dashboard/base.html' %}
{% block content %}

   <!-- PAGE-HEADER -->
   <div class="page-header">
    <h1 class="page-title">Editor-Table</h1>
   
   </div>
<!-- PAGE-HEADER END -->

<!-- Row -->
<div class="main-content app-content mt-0">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Basic Edit Table</h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered border text-nowrap mb-0" id="basic-edit">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>   
                            </tr>
                        </thead>
                        <tbody>
                            {% for r in regions %}
                            <tr>
                                <td>#</td> 
                                <td>{{r.name}}</td>
                                <td><a href="{% url 'dashboard:regions'  %}">Details</a></td>
                            </tr>
                            {% endfor %}
   
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Row -->








{% endblock %}